---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: cp4i-client
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "300"
spec:
  destination:
    namespace: ibm-cloudpaks
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /spec/source/repoURL
        - /spec/source/targetRevision
        - /status
      kind: Application
  project: default
  source:
    path: config/cloudpaks/cp4i/client/base
    repoURL: https://github.com/joehuizenga/cloudpak-gitops.git
  syncPolicy: {}
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
