---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  name: node
  namespace: ibm-cloudpaks
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 12-slim
      annotations:
        openshift.io/imported-from: node:12-slim
      from:
        kind: DockerImage
        name: node:12-slim
      importPolicy: {}
      referencePolicy:
        type: Source
